apiVersion: v1
kind: Secret
metadata:
  name: bloodbridge-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgres://bloodbridge:password@postgres-postgresql.database.svc.cluster.local:5432/bloodbridge?sslmode=disable"
  JWT_SECRET: "dev-secret"
  REDIS_URL: "redis://default:password@redis-master.database.svc.cluster.local:6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.database.svc.cluster.local:5672"